services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    networks:
      - network_
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
    networks:
      - network_
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    networks:
      - network_
    env_file:
      - .env
    volumes:
      - pgdata:/data/db

networks:
  network_:
    driver: bridge

volumes:
  pgdata: {}
