services:
  postgres:
    container_name: postgres
    ports:
      - "5431:5432"
    expose:
      - "5431"
    image: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./docker_test_db:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    expose:
      - "5001"
    command: bash -c "npx prisma db push && npm run dev"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      PORT: "${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: bash -c "npm run preview"
    environment:
      VITE_TARGET_URL: "${VITE_TARGET_URL}"
    ports:
      - 4173:4173
    depends_on:
      - server
