---
- name: Start Chat App
  hosts: ec2
  become: true
  gather_facts: False

  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Remove Stoped docker containers
      shell: |
        docker rm $(docker ps -a -q);
      when: docker_info.containers != 0

    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info

    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"

    - name: update a github repository
      git:
        repo: https://github.com/niklasfulle/chat-app.git
        dest: /chat-app
        clone: no
        update: yes

    - name: deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /chat-app
        files:
          - docker-compose.yml
