---
- name: AWS-Docker-Ansible Stop
  hosts: ec2
  connection: local
  gather_facts: False

  vars_files:
    - vars.yml

  tasks:
    - name: terminate all running instances
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: absent
        filters:
          instance-state-name: running

      tags:
        - ec2_delete_all
        - ec2_terminate
